title: freecad-headphone-tidy
hero_image: images/banner.png
description: freecad-headphone-tidy description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-08"
steps:
  - title: Introduction
  - title: Create the initial sketch
  - title: Revolve the sketch
  - title: Sketch and revolve the upper part
  - title: Cut a hole
  - title: Sketch the cable cut-out
  - title: Create polar pockets
  - title: Export your headphone tidy
  - title: Print your headphone tidy
