title: freecad-headphone-tidy
hero_image: images/banner.png
description: freecad-headphone-tidy description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-08"
steps:
  - title: Introduction
  - title: The initial sketch
  - title: Revolve the sketch
  - title: Sketch and revolve the upper part
  - title: Cutting a hole
